apiVersion: v1
kind: PersistentVolume
metadata:
  name: your-app-back-sessao-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/tmp"  # Altere para o caminho desejado no seu sistema de arquivos
