apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app-front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-app-front
  template:
    metadata:
      labels:
        app: your-app-front
        name: your-app-front
    spec:
      containers:
        - name: your-app-front-container
          image: aluracursos/portal-noticias:1 #configurar // coloque sua imagem
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: env-configmap
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 10m