apiVersion: v1
kind: PersistentVolume
metadata:
  name: your-app-back-images-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/var/www/html/uploads"  # Altere para o caminho desejado no seu sistema de arquivos
