# Deploy da aplicacao com volume.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: your-app-back-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-app-back
  template:
    metadata:
      labels:
        app: your-app-back
    spec:
      containers:
        - name: your-app-back-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: env-configmap
          volumeMounts:
            - name: imagens
              mountPath: "/var/www/html/uploads"
            - name: sessao
              mountPath: "/tmp"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /inserir_noticias.php
              port: 80
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
      volumes:
        - name: imagens
          persistentVolumeClaim:
            claimName: your-app-back-images
        - name: sessao
          persistentVolumeClaim:
            claimName: your-app-back-sessao
