# LoadBalancer Service para acessar a aplicacao
apiVersion: v1
kind: Service
metadata:
  name: your-app-front-service
spec:
  selector:
    app: your-app-front
  ports:
    - port: 30000
      protocol: TCP
      targetPort: 30000
  type: LoadBalancer