apiVersion: v1
kind: PersistentVolume
metadata:
  name: your-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/var/lib/mysql"  # Altere para o caminho desejado no seu sistema de arquivos
