# ClusterIP Service para acessar o banco de dados apenas por dentro do kubernetes
apiVersion: v1
kind: Service
metadata:
  name: your-db-service
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: your-db
  type: ClusterIP